config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "pages/home", to: 'pages#home'

  resources :recipes do
    resources :comments, only: [:create]
    member do
      post 'like'
    end
  end

  get "/signup", to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except: [:destroy]

  mount ActionCable.server => "/cable"
  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]
end

app/views/pages/home.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <%= link_to raw('My Recipes <span class="fa fa-cutlery"></span> '), root_path, class: "navbar-brand",id: "logo" %>
              <nav>
                <ul class="nav masthead-nav">
                  <li><%= link_to "All Recipes", recipes_path %></li>
                  <li><%= link_to "Chefs", chefs_path %></li>
                  <li class="active"><%= link_to "Log in", login_path %></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Welcome to MyRecipes.</h1>
            <p class="lead"><strong>Find & Share Great Recipes</strong></p>
            <p class="lead">
              <%= link_to "Get Started Today", signup_path, class: "btn btn-lg btn-default" %>
            </p>
          </div>

        </div>

      </div>

    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>